Bosses:
  - Key: "boss-amphisbaena"
    Names:
      - Text: "Amphisbaena"
  - Key: "boss-sakit"
    Names:
      - Text: "Sakit"
  - Key: "boss-ellmac"
    Names:
      - Text: "Ellmac"
  - Key: "boss-bahamut"
    Names:
      - Text: "Bahamut"
  - Key: "boss-viy"
    Names:
      - Text: "Viy"
  - Key: "boss-palenque"
    Names:
      - Text: "Palenque"
  - Key: "boss-baphomet"
    Names:
      - Text: "Baphomet"
  - Key: "boss-tiamat"
    Names:
      - Text: "Tiamat"
  - Key: "miniboss-peryton"
    Names:
      - Text: "Peryton"
  - Key: "miniboss-zu"
    Names:
      - Text: "Zu"
  - Key: "miniboss-ghost"
    Names:
      - Text: "ghost"
  - Key: "miniboss-anubis"
    Names:
      - Text: "anubis"
  - Key: "miniboss-argus"
    Names:
      - Text: "argus"
  - Key: "miniboss-buer"
    Names:
      - Text: "buer"
  - Key: "miniboss-centimani"
    Names:
      - Text: "centimani"
  - Key: "miniboss-ba"
    Names:
      - Text: "ba"
  - Key: "miniboss-pazuzu"
    Names:
      - Text: "pazuzu"
    KilledValue: 3
  - Key: "miniboss-gyonin"
    Names:
      - Text: "gyonin"
  - Key: "miniboss-chi-you"
    Names:
      - Text: "Chi You"
  - Key: "miniboss-kamaitachi"
    Names:
      - Text: "kamaitachi"
  - Key: "miniboss-nuckelavee"
    Names:
      - Text: "nuckelavee"
  - Key: "miniboss-nuwa"
    Names:
      - Text: "nuwa"
  - Key: "miniboss-oxheadandhorseface"
    Names:
      - Text: "ox head and horse face"
  - Key: "miniboss-red-skeletonse"
    Names:
      - Text: "red skeletons"
  - Key: "miniboss-skanda"
    Names:
      - Text: "skanda"
    KilledValue: 2
  - Key: "miniboss-the-boss"
    Names:
      - Text: "the boss"
    KilledValue: 3
  - Key: "miniboss-thunderbird"
    Names:
      - Text: "thunderbird"
  - Key: "miniboss-vimana"
    Names:
      - Text: "vimana"