# Regular expressions for people greeting tracker in chat  
RecognizedGreetings:
  - '\b(hi|hey|hello)( there)?,? (tracker|betusTracker)\b'
  - "\\b(greetings|hiya|howdy|'sup),? (tracker|betusTracker)\\b"
  - '\bgood (morning|afternoon|evening|day),? (tracker|betusTracker)\b'
  - '\b(morning|afternoon|evening),? (tracker|betusTracker)\b'
  - '\b(HeyGuys|VoHiYo|pkroseHello|betusHey|digita78Wave) (tracker|betusTracker)\b'
  - '\b(betusTracker|tracker) (HeyGuys|VoHiYo|pkroseHello|betusHey)\b'
  - ^tracker!+$
  - '\bT R A C K E R\b'

# Lines for when tracker connects to Twitch chat
# Type: Weighted Possibilities
WhenConnected:
  - Text: "Hey chat"
  - Text: "Hello Twitch chat"
  - Text: "Hey Twitch chat"
  - Text: "Oh no, not the chat. They're the last people I want to see."
    Weight: 0.2
  - Text: "I hope you know I'm paid by the letter when it comes to reading chat."
    Weight: 0.2

UserNamePronunciations:
  MattEqualsCoder: Matt Equals Coder

# The list of possibilities when the streamer greets tracker in chat
# Type: Weighted Possibilities
# {0} is replaced with the chat user's name
GreetedBySelf:
  - Text: "Shouldn't you focus on the seed {0}?"
  - Text: "Is the logic too dull for you {0}?"
  - Text: "Don't you have something better to do {0}?"
  
# The list of possibilities for when a user has greeted tracker in chat
# Type: Weighted Possibilities
# {0} is replaced with the chat user's' name
GreetingResponses:
  - Text: "Hello {0}"
  - Text: "Oh hello {0}. I didn't see you there."
  - Text: "It's about time you showed up {0}."
    Weight: 0.2

# The list of possibilities for when a user has greeted tracker in chat multiple times
# Type: Weighted Possibilities
# {0} is replaced with the chat user's' name
GreetedTwice:
  - Text: "I already said hi to you {0}"
  - Text: "Didn't you already greet me, {0}?"
  
# The list of possibilities when trying to open a prediction poll when not connected to chat
# Type: Weighted Possibilities
NotConnectedToChat:
  - Text: "I'm not currently connected to chat. If you have all of the settings entered, you can say Hey tracker, connect to chat"
      
# The list of possibilities for when trying to close or resolve a prediction poll when there isn't one
# Type: Weighted Possibilities
NoCurrentPrediction:
  - Text: "There is no current prediction poll"
  
# The list of possibilities for when trying to open a prediction poll when one is already open
# Type: Weighted Possibilities
# {0} is replaced with the chat user's' name
PredictionAlreadyExists:
  - Text: "A prediction poll already exists"
    
# The list of possibilities for when a prediction poll was locked
# Type: Weighted Possibilities
PredictionLocked:
  - Text: "Prediction poll was locked for new responses"
  
# The list of possibilities for when a prediction poll was terminated and refunded
# Type: Weighted Possibilities
PredictionCancelled:
  - Text: "Prediction poll was cancelled and all points refunded"

# The list of possibilities for when asking tracker to track content and she opens a poll
# Type: Weighted Possibilities
AskChatAboutContent:
  - Text: "Are you sure that was some high quality content? Let's check with chat to see what they think."
    
# The list of possibilities for when chat voted yes on content
# Type: Weighted Possibilities
AskChatAboutContentYes:
  - Text: "It appears the chat is on your side. They think that was some high quality content"
    
# The list of possibilities for when chat voted no on content
# Type: Weighted Possibilities
AskChatAboutContentNo:
  - Text: "Ouch. The chat did not think that was some high quality content"
    
# The list of possibilities for when the poll results come back from chat
# Type: Weighted Possibilities
PollComplete:
  - Text: "And the results are now in."
    
# The list of possibilities for when tracker successfully opened a twitch poll
# Type: Weighted Possibilities
# {0} is replaced with the number of seconds the poll is open for
PollOpened:
  - Text: "I have opened a poll for {0} seconds."
    
# The list of possibilities for when tracker couldn't get the poll results
# Type: Weighted Possibilities
PollError:
  - Text: "Sorry, I was unable to get the poll results."

# The list of tiered responses for when content is being tracked
# Type: Rollup Responses
ContentTracked:
  1:
    - Text: "Congrats on your first con-tent"
    - Text: "Your first con-tent is always special"
  2:
    - Text: "More than one con-tent in a run? What a shock."
    - Text: "Congrats on getting your {1} content"
  5:
    - Text: "Don't you think this is too much con-tent?"
    - Text: "I think you may be lying about this much con-tent."
    - Text: "Good job on getting {0} con-tent"

# The list of different prediction polls that can be added
  # StartPrompts: The prompts to initiate the prediction poll (without "Hey Tracker" added to the beginning)
    # Type: List of Strings
  # ResolveGoodPrompts: The prompts to resolve the prediction poll with the "good" result (without "Hey Tracker" added to the beginning)
    # Type: List of Strings
  # ResolveBadPrompts: The prompts to resolve the prediction poll with the "bad" result (without "Hey Tracker" added to the beginning)
    # Type: List of Strings
  # StartResponses: The list of possibilities for when tracker starts the prediction poll
    # Type: Weighted Possibilities
  # PredictionTitles: The list of titles to show up on the Twitch prediction poll
    # Type: Weighted possibilties
  # PredictionOptions: The list of possible options for people to select from. (Max 25 characters.)
    # Type: Has the two fields "Good" and "Bad" which are the two options people can select on Twitch
    # Example:
      # - Good: It'll be great
      #   Bad: It'll suck!
      # - Good: I expect greatness!
      #   Bad: I expect suckiness!
  # ResolvedResponses: The list of possibilities for when tracker resolves the prediction poll
    # Type: Weighted possibilities
    # {0} is replaced with the winning choice
    # {1} is replaced with the number of people who voted for the winning choice
    # {2} is replaced with the number of points spent on the winning choice
    # {3} is replaced with the name of someone who voted on the winning choice
    # {4} is replaced with the number of people who voted for the losing choice
    # {5} is replaced with the number of points spent on the losing choice
    # {6} is replaced with the name of someone who voted on the losting choice
  # DurationSeconds: Number of seconds the prediction poll should last (defaults to 120 seconds)
Predictions:
